data_cfg:
  input_dir: E:\dataset\Structured3D\
  train_file: E:\python_project\OpenPanoDepth\datasets\structure3d\train_structure3d.txt
  test_file: E:\python_project\OpenPanoDepth\datasets\structure3d\test_structure3d.txt
  name: stanford2d3d
  train_batch_size: 2
  test_batch_size: 2
  shuffle: True
  num_workers: 8
  type: high

model_cfg:
  model: Bifusev2_self
#  load_checkpoint: None
  load_checkpoint: E:\python_project\OpenPanoDepth\result\Bifusev2_self\checkpoints\checkpoint_best.pth

  base_config:
     save_path: E:\\python_project\\OpenPanoDepth\\result\\Bifusev2_self
     dnet_args:
          layers: 34
          CE_equi_h: [ 8, 16, 32, 64, 128, 256, 512 ]
     pnet_args:
          layers: 18
          nb_tgts: 2


worker_cfg:
  epochs: 50
  visualize_interval: 20
  save_checkpoint: E:\\python_project\\OpenPanoDepth\\result\\Bifusev2_self\\checkpoints
  save_path: E:\\python_project\\OpenPanoDepth\\result\\Bifusev2_self

  optimizer_cfg:
    solver: AdamW
    lr: 0.0002
    betas: (0.9, 0.999)
    weight_decay: 0.01

  scheduler_cfg:
    T_0: 5
    T_mult: 2
    eta_min: 1e-6
    last_epoch: -1


  evaluator_cfg:
    metric:
      - abs_
      - abs_rel
      - sq_rel
      - rms
      - rms_log
      - log10
      - a1
      - a2
      - a3