data_cfg:
  input_dir: E:\\dataset\\2D3Ds
  test_file: E:\\python_project\\OpenPanoDepth\\datasets\\stanford2d3d\\test_stanford2d3d.txt
  name: stanford2d3d
  test_batch_size: 1
  shuffle: True
  num_workers: 8
  type: high

model_cfg:
  model: PanoFormer
  load_checkpoint: E:\python_project\OpenPanoDepth\openpano\modeling\PanoFormer\per_models\model.pth

  base_config:
    img_size: 256
    in_chans: 3
    embed_dim: 32
    depths: [2, 2, 2, 2, 2, 2, 2, 2, 2]
    num_heads: [1, 2, 4, 8, 16, 16, 8, 4, 2]
    win_size: 8
    mlp_ratio: 4.
    qkv_bias: True
    qk_scale: None
    drop_rate: 0.
    attn_drop_rate: 0.
    drop_path_rate: 0.1
    patch_norm: True
    use_checkpoint: False
    token_projection: 'linear'
    token_mlp: 'leff'
    se_layer: False

worker_cfg:
  save_path: E:\\python_project\\OpenPanoDepth\\result\\PanoFormer
  evaluator_cfg:
    metric:
      - abs_
      - abs_rel
      - sq_rel
      - rms
      - rms_log
      - log10
      - a1
      - a2
      - a3
