data_cfg:
  input_dir: E:\\dataset\\2D3Ds
  train_file: E:\\python_project\\OpenPanoDepth\\datasets\\stanford2d3d\\train_stanford2d3d.txt
  test_file: E:\\python_project\\OpenPanoDepth\\datasets\\stanford2d3d\\test_stanford2d3d.txt
  name: stanford2d3d
  train_batch_size: 4
  test_batch_size: 4
  shuffle: True
  num_workers: 8
  type: low

model_cfg:
  model: EGformer
#  load_checkpoint: E:\python_project\OpenPanoDepth\result\Omnifusion_try\checkpoints\checkpoint_latest.pth
  load_checkpoint: None

  base_config:
    img_size: [256, 512]
    patch_size: 4
    in_chans: 3
    num_classes: 1000
    embed_dim: 32
    depth: [2, 2, 2, 2, 2, 2, 2, 2, 2]
    split_size: [1,1,1,1,1,1,1,1,1]
    num_heads: [1,2,4,8,8,4,2,1,16]
    mlp_ratio: 4.
    qkv_bias: True
    qk_scale: None
    drop_rate: 0.
    attn_drop_rate: 0.
    drop_path_rate: 0.
    hybrid_backbone: None
    use_chk: False
    hybrid: False


worker_cfg:
  epochs: 20
  visualize_interval: 20
  save_checkpoint: E:\\python_project\\OpenPanoDepth\\result\\EGformer\\checkpoints
  save_path: E:\\python_project\\OpenPanoDepth\\result\\EGformer

  optimizer_cfg:
    solver: AdamW
    lr: 0.0002
    betas: (0.9, 0.999)
    weight_decay: 0.01

  scheduler_cfg:
    T_0: 5
    T_mult: 2
    eta_min: 1e-6
    last_epoch: -1


  evaluator_cfg:
    metric:
      - abs_
      - abs_rel
      - sq_rel
      - rms
      - rms_log
      - log10
      - a1
      - a2
      - a3