data_cfg:
  input_dir: E:\\dataset\\2D3Ds
  test_file: E:\\python_project\\OpenPanoDepth\\datasets\\stanford2d3d\\test_stanford2d3d.txt
  name: stanford2d3d
  test_batch_size: 2
  shuffle: True
  num_workers: 8
  type: high

model_cfg:
  model: SliceNet
  load_checkpoint: E:\python_project\OpenPanoDepth\openpano\modeling\SliceNet\per_model\resnet50_stanford.pth

  base_config:
    backbone: 'resnet50'


loss_cfg:
  # This model uses the user-defined loss function.


worker_cfg:
  save_path: E:\\python_project\\OpenPanoDepth\\result\\SliceNet
  evaluator_cfg:
    metric:
      - abs_
      - abs_rel
      - sq_rel
      - rms
      - rms_log
      - log10
      - a1
      - a2
      - a3