data_cfg:
  input_dir: E:\dataset\Structured3D\
  test_file: E:\python_project\OpenPanoDepth\datasets\structure3d\test_structure3d.txt
  name: stanford2d3d
  test_batch_size: 1
  shuffle: True
  num_workers: 8
  type: low

model_cfg:
  model: HRDFuse
  load_checkpoint: E:\python_project\OpenPanoDepth\result\HRDFuse\checkpoints\checkpoint_best.pth

  base_config:
    nrows: 4
    npatches_dict: { 3: 10, 4: 18, 5: 26, 6: 46 }
    patch_size: 256
    fov: 80
    nbins: 100
    min_val: 0.1
    max_val: 10


worker_cfg:
  save_path: E:\\python_project\\OpenPanoDepth\\result\\HRDFuse
  evaluator_cfg:
    metric:
      - abs_
      - abs_rel
      - sq_rel
      - rms
      - rms_log
      - log10
      - a1
      - a2
      - a3