data_cfg:
  input_dir: E:\\dataset\\2D3Ds
  test_file: E:\\python_project\\OpenPanoDepth\\datasets\\stanford2d3d\\test_stanford2d3d.txt
  name: stanford2d3d
  test_batch_size: 2
  shuffle: False
  num_workers: 8
  type: high

model_cfg:
  model: Omnifusion
  load_checkpoint: E:\python_project\OpenPanoDepth\openpano\modeling\Omnifusion\per_models\Stanford_2iter.pth

  base_config:
    patch_size: (256,256)
    fov: 80
    nrows: 4
    iter: 2
    npatches_dict: { 3: 10, 4: 18, 5: 26, 6: 46 }

worker_cfg:
  save_path: E:\\python_project\\OpenPanoDepth\\result\\Omnifusion_iter2
  evaluator_cfg:
    metric:
      - abs_
      - abs_rel
      - sq_rel
      - rms
      - rms_log
      - log10
      - a1
      - a2
      - a3