data_cfg:
  input_dir: E:\dataset\Structured3D\
  test_file: E:\python_project\OpenPanoDepth\datasets\structure3d\test_structure3d.txt
  name: stanford2d3d
  train_batch_size: 1
  test_batch_size: 1
  shuffle: True
  num_workers: 8
  type: low

model_cfg:
  model: GLPanoDepth
  load_checkpoint: E:\python_project\OpenPanoDepth\result\GLPanoDepth\checkpoints\checkpoint_best.pth


  base_config:
    image_height: 256
    image_width: 512


worker_cfg:
  save_path: E:\\python_project\\OpenPanoDepth\\result\\GLPanoDepth
  evaluator_cfg:
    metric:
      - abs_
      - abs_rel
      - sq_rel
      - rms
      - rms_log
      - log10
      - a1
      - a2
      - a3